services:
  postgres:
    container_name: postgres
    image: postgres:17.2-alpine3.20
    networks:
      - bank-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  bank-network:
    external: true

