name: CI-Test

on:
  # workflow_dispatch:
  #   inputs:
  #     parameter1:
  #       description: "Deskripsi parameter opsional"
  #       required: false
  #       default: "default_value"
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:17.2-alpine3.20
        ports:
          - "5432:5432"
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install Golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run Migrations
        run: make migrateup

      - name: Test
        run: make test
